import { YouTubeChannel, YouTubeApiKey, YouTubeVideo, QueueState } from '../../types/youtube';
import React from 'react';

export interface YouTubeMonitorHeaderControlsProps {
  isDark: boolean;
  appLang: 'en' | 'bn';
  queueState: QueueState;
  isMobileMenuOpen: boolean;
  setIsMobileMenuOpen: (val: boolean) => void;
  isLinkModalOpen: boolean;
  setIsLinkModalOpen: (val: boolean) => void;
  isSelectMode: boolean;
  setIsSelectMode: (val: boolean) => void;
  clearSelection: () => void;
  selectedIds: string[];
  filterRef: React.RefObject<HTMLDivElement>;
  showFilterMenu: boolean;
  setShowFilterMenu: (val: boolean) => void;
  setShowChannelSettings: (val: boolean) => void;
  setShowApiSettings: (val: boolean) => void;
  setShowMonitorSettings: (val: boolean) => void;
  setShowVoiceSettings: (val: boolean) => void;
  selectedChannelFilter: string;
  setSelectedChannelFilter: (val: string) => void;
  selectedDurationFilter: string;
  setSelectedDurationFilter: (val: string) => void;
  selectedDateFilter: string;
  setSelectedDateFilter: (val: string) => void;
  selectedTimeFilter: string;
  setSelectedTimeFilter: (val: string) => void;
  selectedStatusFilter: string;
  setSelectedStatusFilter: (val: string) => void;
  channels: YouTubeChannel[];
  monitorFilter: 'all' | 'unread' | 'archive';
  setMonitorFilter: (val: 'all' | 'unread' | 'archive') => void;
  searchQuery: string;
  setSearchQuery: (val: string) => void;
  channelRef: React.RefObject<HTMLDivElement>;
  showChannelSettings: boolean;
  newChannelTitle: string;
  setNewChannelTitle: (val: string) => void;
  newChannelId: string;
  setNewChannelId: (val: string) => void;
  handleAddChannel: () => void;
  editingChannelId: string | null;
  setEditingChannelId: (val: string | null) => void;
  editChannelTitle: string;
  setEditChannelTitle: (val: string) => void;
  editChannelValue: string;
  setEditChannelValue: (val: string) => void;
  handleSaveChannel: (id: string) => void;
  removeChannel: (id: string) => void;
  handleMarkAllRead: () => void;
  toggleAutoProcess: () => void;
  toggleAutoDownload: () => void;
  fetchVideos: () => void;
  isFetching: boolean;
  monitorRef: React.RefObject<HTMLDivElement>;
  showMonitorSettings: boolean;
  showVoiceSettings: boolean;
  isVoiceEnabled: boolean;
  toggleVoice: (val: boolean) => void;
  voices: {voiceURI: string, name: string, lang: string}[];
  selectedVoiceURI: string;
  selectVoice: (val: string) => void;
  announce: (text: string) => void;
  isSpeaking: boolean;
  apiRef: React.RefObject<HTMLDivElement>;
  showApiSettings: boolean;
  apiKeys: YouTubeApiKey[];
  newApiLabel: string;
  setNewApiLabel: (val: string) => void;
  newApiKey: string;
  setNewApiKey: (val: string) => void;
  handleAddKey: () => void;
  editingApiKeyId: string | null;
  setEditingApiKeyId: (val: string | null) => void;
  editApiLabel: string;
  setEditApiLabel: (val: string) => void;
  editApiValue: string;
  setEditApiValue: (val: string) => void;
  handleSaveApiKey: (id: string, updates?: Partial<YouTubeApiKey>) => void;
  removeApiKey: (id: string) => void;
  handleBulkDownload: () => void;
  handleBulkMarkRead: () => void;
  handleBulkStart: () => void;
  handleBulkStop: () => void;
  handleBulkClearDownload: () => void;
  handleBulkDelete: () => void;
}
